customer/urls.py
from django.urls import path

urlpatterns = []

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, cart, checkout, order

app_name = "store"

urlpatterns = [
    # path("", views.home, name="home"),
    path("", cart.wishlist_view, name="home"),
    # path("", views.category, name="home"),
    path("category/", views.category, name="category"),
    path("product/<str:slug>", views.product_list, name="product_list"),
    path(
        "product/<str:cat_slug>/<str:prd_id>",
        views.product_detail,
        name="product_detail",
    ),
    # 제품검색
    # path("search", views.search_ajax),
    # path("searchproducts", views.searchproducts, name="searchproducts"),
    path("search/", views.search, name="search"),
    # Cart
    path("add-to-cart", cart.addtocart, name="addtocart"),
    path("cart", cart.viewcart, name="cart"),
    path("update-cart", cart.updatecart, name="updatecart"),
    path("delete-cart-item", cart.deletecartitem, name="deletecartitem"),
    # 주문
    path("checkout", checkout.index, name="checkout"),
    path("place-order", checkout.place_order, name="place_order"),
    # 주문상세내역
    path("my-orders", order.my_orders, name="myorders"),
    path("order-view/<str:tk_no>", order.order_view, name="orderview"),
    path("my-orders/<str:tk_no>", order.order_cancel, name="order_cancel"),
    # path("export_csv/<str:tk_no>", order.export_csv, name="export_csv"),
    # path("export_pdf/<str:tk_no>", order.export_pdf, name="export_pdf"),
    # 자주주문내역
    path("wish_list", cart.wishlist_view, name="wishlist_view"),
    path("add_to_wishlist", cart.add_to_wishlist, name="add_to_wishlist"),
    path("delete_wish_item", cart.delete_wishitem, name="delete_wishitem"),
    path("add_wish_to_cart", cart.add_wish_to_cart, name="add_wish_to_cart"),
    # Language code
    # path('/language/<str:language_code>', views.set_language, name='set_language'),
]

storeman/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    admin_home,
    export_csv,
    export_pdf,
)
from .product_man import (
    product_list,
    create_product,
    display_product_detail,
    edit_product,
    delete_product,
)
from .address_man import (
    create_customer_address,
    edit_customer_address,
    delete_customer_address,
)
from .customer_man import (
    display_customer_list,
    display_customer_details,
    create_customer,
    edit_customer,
    delete_customer,
)

from .order_man import (
    order_list,
    create_order,
    order_details,
    submit_order,
    daily_order,
    order_list_detail,
)

from .staff_man import (
    display_staff,
    create_staff,
    create_driver,
    edit_staff,
)

from .delivery_man import (
    display_delivery_team,
    edit_delivery_team,
)

app_name = "storeman"

urlpatterns = [
    # Order
    path("", admin_home, name="admin_home"),
    path("order_list/", order_list, name="order_list"),
    path("order_list_detail/<str:pk_id>", order_list_detail, name="order_list_detail"),
    path("daily_order/", daily_order, name="daily_order"),
    path("submit_order/", submit_order, name="submit_order"),
    path("create_order/", create_order, name="create_order"),
    path("order_details/<str:tk_no>", order_details, name="order_details"),
    path("export_csv/<str:tk_no>", export_csv, name="export_csv"),
    path("export_pdf/<str:tk_no>", export_pdf, name="export_pdf"),
    path("display_customer_list/", display_customer_list, name="display_customer_list"),
    path(
        "display_customer_details/<str:pk_id>",
        display_customer_details,
        name="display_customer_details",
    ),
    path(
        "create_customer_address/<str:pk_id>",
        create_customer_address,
        name="create_customer_address",
    ),
    path(
        "edit_customer_address/<str:pk_id>/<str:addr_id>",
        edit_customer_address,
        name="edit_customer_address",
    ),
    path(
        "delete_customer_address/<str:pk_id>/<str:addr_id>",
        delete_customer_address,
        name="delete_customer_address",
    ),
    path("create_customer/", create_customer, name="create_customer"),
    path("edit_customer/<str:pk_id>", edit_customer, name="edit_customer"),
    path("delete_customer/<str:pk_id>", delete_customer, name="delete_customer"),
    path("submit_order/", submit_order, name="submit_order"),
    # Product
    path("create_product/", create_product, name="create_product"),
    path("product_list/", product_list, name="product_list"),
    path(
        "display_product_detail/<str:pk_id>",
        display_product_detail,
        name="display_product_detail",
    ),
    path("edit_product/<str:pk_id>", edit_product, name="edit_product"),
    path("delete_product/<str:pk_id>", delete_product, name="delete_product"),
    # Staff
    path("display_staff/", display_staff, name="display_staff"),
    path("create_staff/", create_staff, name="create_staff"),
    path("edit_staff/<str:pk_id>", edit_staff, name="edit_staff"),
    path("create_driver/<str:pk_id>", create_driver, name="create_driver"),
    # Delivery
    path("display_delivery_team/", display_delivery_team, name="display_delivery_team"),
    path(
        "edit_delivery_tean/<str:pk_id>", edit_delivery_team, name="edit_delivery_team"
    ),
]

customer/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


ROLE_CHOICES = (
    ("ADMIN", "Admin"),
    ("MANAGER", "Manager"),
    ("DRIVER", "Driver"),
    ("CUSTOMER", "Customer"),
)


class User(AbstractUser):
    phone = models.CharField(max_length=10, unique=True, null=True)
    role = models.CharField(
        max_length=10, choices=ROLE_CHOICES, default=None, blank=True, null=True
    )

    def __str__(self):
        return f"{self.username}"

storeman/models.py
from django.db import models

# from storeman.models import CreateUserOrder
from store.models import Product
from customer.models import User
from company.models import AddressBook


class UserOrder(models.Model):
    STATUS = (
        ("Pending", "Pending"),
        ("Out for delivery", "Out for delivery"),
        ("Delivered", "Delivered"),
    )
    customer = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    address = models.ForeignKey(AddressBook, null=True, on_delete=models.SET_NULL)
    status = models.CharField(
        max_length=200, null=True, default="Pending", choices=STATUS
    )
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"self.customer"


class UserOrderItem(models.Model):
    order = models.ForeignKey(UserOrder, null=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE)
    quantity = models.IntegerField(null=True)

    def __str__(self):
        return f"self.order"

customer/views.py
from django.shortcuts import render

# Create your views here.

storeman/views.py
import base64
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.shortcuts import render, redirect
from django.http import HttpResponse
from store.models import Order, OrderItem
from delivery.models import StaffMember

from customer.models import User
from company.models import AddressBook
from store.models import Product, OrderCode
from .tools import *


import csv
import codecs
from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile
from datetime import datetime, date
import pandas as pd
import os, pytz


au_timezone = pytz.timezone("Australia/Sydney")
today = date.today()
now = datetime.now(au_timezone)
now_year = now.year
now_month = now.month
now_day = now.day
this_monday = get_this_monday()
this_friday = get_this_friday()
last_monday = get_last_monday()
last_friday = get_last_friday()
this_month_start = get_this_month_start()
this_month_end = get_this_month_end()
last_month_start = get_last_month_start()
last_month_end = get_last_month_end()
# from store.utils import xhtml_render_to_pdf, weasypdf_render_to_pdf


@login_required(login_url="account_login")
def admin_home(request):
    if not request.user.is_staff | request.user.is_superuser:
        return redirect("/login")
    order_item = OrderItem.objects.filter(order__status="Delivered")
    staffs = StaffMember.objects.all()
    order_team = Order.objects.values("driver_team").filter(
        updated_at__year=now_year,
        updated_at__month=now_month,
        updated_at__day=now_day,
    )
    east_team = order_team.aggregate(
        count=Count("driver_team", filter=Q(driver_team="동부팀"))
    )
    west_team = order_team.aggregate(
        count=Count("driver_team", filter=Q(driver_team="서부팀"))
    )
    south_team = order_team.aggregate(
        count=Count("driver_team", filter=Q(driver_team="남부팀"))
    )
    north_team = order_team.aggregate(
        count=Count("driver_team", filter=Q(driver_team="북부팀"))
    )
    pending_order = Order.objects.filter(status="Pending").count()
    on_delivery = Order.objects.filter(status="Out for delivery").count()
    delivered = Order.objects.filter(
        status="Delivered",
        updated_at__year=now_year,
        updated_at__month=now_month,
        updated_at__day=now_day,
    )
    daily_delivered = delivered.aggregate(
        count=Count("status", filter=Q(status="Delivered"))
    )
    this_weekly_delivered_qs = Order.objects.filter(
        status="Delivered", updated_at__range=[this_monday, this_friday]
    )
    this_weekly_delivered = this_weekly_delivered_qs.aggregate(
        count=Count("status", filter=Q(status="Delivered"))
    )
    last_weekly_delivered = Order.objects.filter(
        status="Delivered", updated_at__range=[last_monday, last_friday]
    ).count()

    this_monthly_delivered = Order.objects.filter(
        status="Delivered", updated_at__range=[this_month_start, this_month_end]
    ).count()

    last_monthly_delivered = Order.objects.filter(
        status="Delivered", updated_at__range=[last_month_start, last_month_end]
    ).count()

    yearly_delivered = Order.objects.filter(
        status="Delivered", updated_at__year=now_year
    ).count()

    context = {
        "east_team": east_team,
        "west_team": west_team,
        "south_team": south_team,
        "north_team": north_team,
        "order_item": order_item,
        "pending_order": pending_order,
        "on_delivery": on_delivery,
        "daily_delivered": daily_delivered,
        "this_weekly_delivered": this_weekly_delivered,
        "last_weekly_delivered": last_weekly_delivered,
        "this_monthly_delivered": this_monthly_delivered,
        "last_monthly_delivered": last_monthly_delivered,
        "yearly_delivered": yearly_delivered,
    }
    return render(request, "storeman/dashboard.html", context)


@login_required(login_url="account_login")
def export_csv(request, tk_no):
    if not request.user.is_staff | request.user.is_superuser:
        return redirect("/login")
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = "attachment;filename=ami" + f"-{tk_no}.csv"
    response.write(codecs.BOM_UTF8)
    writer = csv.writer(response)
    writer.writerow(["주문일자", "주문업체코드", "주문업체명", "제품코드", "제품명", "수량"])
    order = Order.objects.filter(tracking_no=tk_no).first()
    orderitems = OrderItem.objects.filter(order=order)
    for item in orderitems:
        writer.writerow(
            [
                item.order.created_at.strftime("%Y-%m-%d"),
                item.order.user.number,
                item.order.user.company_name,
                item.product.bar_code,
                item.product.title,
                item.quantity,
            ]
        )
    return response


@login_required(login_url="account_login")
def export_pdf(request, tk_no):
    if not request.user.is_staff | request.user.is_superuser:
        return redirect("/login")
    with open("media/order/barcode/" + f"{tk_no}.png", "rb") as img:
        encoded_string = base64.b64decode(img.read())
    response = HttpResponse(content_type="application/pdf")
    # 화면에 먼저 보여주기 inline; 추가
    response["Content-Disposition"] = "inline; attachment;filename=" + f"{tk_no}.pdf"
    response["Content-Transfer-Encoding"] = "binary"
    order = Order.objects.filter(tracking_no=tk_no).first()
    orderitems = OrderItem.objects.filter(order=order)
    # delivery_method = OrderCode.objects.get(code=order.order_code)
    for item in orderitems:
        item_code = item.order_code
        item_type = item.order_type
    company_name = order.company_name
    company_e_name = order.company_e_name
    first_name = order.user.first_name
    last_name = order.user.last_name
    phone = order.user.phone
    city = order.city
    order_date = order.created_at
    # order_category = orderitems.product.category
    # order_code = item_code
    order_type = item_type
    total_price = order.total_price
    message = order.message

    # delivery_instructions = delivery_method.delivery_instructions
    html_string = render_to_string(
        "storeman/pdf-output.html",
        {
            "orderitems": orderitems,
            "tk_no": tk_no,
            "company_name": company_name,
            "company_e_name": company_e_name,
            "first_name": first_name,
            "last_name": last_name,
            "city": city,
            "phone": phone,
            "order_date": order_date,
            # "order_code": order_code,
            "order_type": order_type,
            "total_price": total_price,
            # "order_category": order_category,
            "message": message,
        },
    )

    html = HTML(string=html_string, base_url=request.build_absolute_uri())

    result = html.write_pdf()

    with tempfile.NamedTemporaryFile(delete=False) as output:
        output.write(result)
        output.flush()
        output = open(output.name, "rb")
        response.write(output.read())

    return response

templates/storeman/customer/create_customer.html
{% extends '../admin_base.html' %}
{% load widget_tweaks %}

{% block content %}
{% comment %} <div class="container">
    {% if form.errors %}
    <div class="alert alert-danger">
        <strong>에러!</strong> 비밀번호 또는 필수항목이 빠졌습니다. 
      </div>
    {% endif %} {% endcomment %}
<!--Start card-->
<div class="container">
    <div class="card p-2">
        <div class="card-header text-center">
        <h5>고객등록</h5>
        </div>
<!--Card body-->
        <div class="card-body">
            <form method="post">
            <div class="row">
                {% csrf_token %}
            <div class="col-md-6 mb-0">
                <label>사용자ID</label>
                {% render_field form.username placeholder="사용자ID" class+="form-control" %}
                {{form.username.errors}}
                
            </div>
            <div class="col-md-6 mb-0">
                <label>이메일</label>
                {% render_field form.email placeholder="이메일" class+="form-control" %}
                {{form.email.errors}}
            </div>
        </div>
        <div class="row">
            <div class="form-group col-4 mb-0">
                <label>이름</label>
                {% render_field form.first_name placeholder="이름" class+="form-control" %}
                {{form.first_name.errors}}
            </div>
            <div class="form-group col-4 mb-0">
                <label>성명</label>
                {% render_field form.last_name placeholder="성명" class+="form-control" %}
                {{form.last_name.errors}}
            </div>
            <div class="form-group col-4 mb-0">
                <label>연락처</label>
                {% render_field form.phone placeholder="연락처" class+="form-control" %}
                {{form.phone.errors}}
            </div> 
        </div>
        <div class="row">
            <div class="form-group col-4 mb-0">
                <label>비밀번호</label>
                {% render_field form.password1 placeholder="비밀번호" class+="form-control" %}
                {{form.password1.errors}}
            </div> 
            <div class="form-group col-4 mb-0">
                <label>비밀번호확인</label>
                {% render_field form.password2 placeholder="비밀번호확인" class+="form-control" %}
                {{form.password2.errors}}
            </div> 
            <div class="form-group col-4 mb-0">
                <label>역할</label>
                {% render_field form.role placeholder="역할" class+="form-control" %}
                {{form.password2.errors}}
            </div> 
        </div>
    </div>
    <!--End Card body-->
    <!--Card footer-->
        <div class="card-footer">
            <button  class="btn btn-outline-danger me-3" type="cancel"><a href="{% url "storeman:create_customer" %}">취소</a></button>
            <button  class="btn btn-outline-success" type="sumbit">등록</button>
            <button class="btn btn-outline-primary float-end"><a href="{% url "storeman:display_customer_list" %}">이전</a></button> 
        </div>
<!--End Card footer-->
       </form>
    </div>
<!--End card-->
</div>
{% endblock content %}

templates/storeman/customer/create_customer_address.html
{% extends '../admin_base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content  %}
<div class="container">
   <form method="POST">
      {% csrf_token %} 
      {{ formset.management_form}}
      {% for form in formset %}
      <div class="card mt-2">
         <div class="card-header">
            주소 # {{forloop.counter}}
         </div>
         <div class="card-body">
            {{form|crispy}}
         </div>
         
         <div class="card-footer p-2 mt-2">
            <button class="btn btn-info" type="submit">등록</button>
         </div>
      </div>
      {% endfor %}
   </form>
      

</div>
{% endblock %}

templates/storeman/customer/display_customer_details.html
{% extends '../admin_base.html' %}

{% block content  %}
<div class="container p-3">
    <div class="align-baseline">
        <a href="{% url 'storeman:create_customer_address' customer.id %}" class="btn btn-info"><i
                class="bi bi-plus"></i> 배송지추가</a>
        <a href="{% url 'storeman:display_customer_list' %}" class="btn btn-info float-end"><i
                class="fa-solid fa-left-long"></i> 이전</a>
    </div>
    <table class="table table-bordered border-dark text-center mt-2">
        <thead class="bg-light">
            <tr>
                <th>사용자ID</th>
                <th>담당자명</th>
                <th>연락처</th>
                <th>이메일</td>
                <th>역할</td>
                <th>수정</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{customer.username}}</td>
                <td>{{customer.last_name}} {{customer.first_name}}</td>
                <td>{{customer.phone}}</td>
                <td>{{customer.email}}</td>
                <td>{{customer.role}}</td>
                <td>
                    <a href="{% url "storeman:edit_customer" customer.id %}" class="btn btn-sm btn-warning"><i class="bi bi-pencil"></i></a>
                </td>
            </tr>
        </tbody>
    </table>

<table class="table table-bordered border-dark text-center">
        <thead class="bg-light">
            <tr>
                <th>#</th>
                <th>배송지명</th>
                <th>주소</th>
                <th>도시명</th>
                <th>주</th>
                <th>우편번호</th>
                <th>기본배송지</th>
                <th>배송방법</th>
                <th>담당자</th>
                <th>주문코드(일반)</th>
                <th>주문코드(야채)</th>
                <th>수정</th>
            </tr>
        </thead>
        <tbody>
            {% for addr in address %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{ addr.h_name }}({{addr.e_name}})</td>
                <td>{{addr.address}}</td>
                <td>{{addr.city}}</td>
                <td>{{addr.state}}</td>
                <td>{{addr.postcode}}</td>
                <td>{{addr.default}}</td>
                <td>{{addr.delivery_instructions}}</td>
                <td>{{addr.driver}}</td>
                <td>{{addr.gen_code}}</td>
                <td>{{addr.vegi_code}}</td>
                <td>
                    <a href="{% url 'storeman:edit_customer_address' customer.id addr.id %}" class="btn btn-sm btn-warning"><i class="bi bi-pencil"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/storeman/customer/display_customer_list.html
{% extends "../admin_base.html" %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
<div class="card mt-2">
    <div class="card-body">

    </div>
</div>
<div class="card mt-2">
    <table class="table table-hover">
        <thead class="bg-dark text-light">
            <tr>
                <th>#</th>
                <th>사용자ID</th>
                <th>담당자</th>
                <th>이메일</th>
                <th>연락처</th>
                <th>기본배송지</th>
                <th>최근접속</th>
                <th>배송지관리</th>
            </tr>
        </thead>
        <tbody id="customer_Tbody">
            {% for customer in page_obj %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{customer.user.username}}</td>
                <td>{{customer.user.last_name}}{{customer.first_name}}</td>
                <td>{{customer.user.email}}</td>
                <td>{{customer.user.phone}}</td>
                <td>{{customer.h_name}}</td>
                <td>{{customer.user.last_login}}</td>
                <td><a href="{% url 'storeman:display_customer_details' customer.user.id %}" class="btn btn-warning"><i class="bi bi-pencil"></i></a></td>
            </tr>
            {% endfor %}
            
        </tbody>
    </table>
    {% include "../../pagination.html"%}
</div>
</div>
{% endblock %}

templates/storeman/customer/edit_customer.html
{% extends '../admin_base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container p-2">
    <div class="card">
        <div class="card-header">
            <h5>고객ID:  {{customer.username}} 수정</h5>
        </div>
        <div class="card-body">
        <form method='post'>
            <div class="row">
            {% csrf_token %}
                <div class="form-group col-3 mb-0">
                    <label>성명</label>
                    {% render_field form.last_name placeholder="성명" class+="form-control" %}
                    {{form.last_name.errors}}
                </div>
                <div class="form-group col-3 mb-0">
                    <label>이름</label>
                    {% render_field form.first_name placeholder="이름" class+="form-control" %}
                    {{form.first_name.errors}}
                </div>
                <div class="col-md-3 mb-0">
                    <label>이메일</label>
                    {% render_field form.email placeholder="이메일" class+="form-control" %}
                    {{form.email.errors}}
                </div>
                <div class="form-group col-3 mb-0">
                    <label>연락처</label>
                    {% render_field form.phone placeholder="연락처" class+="form-control" %}
                    {{form.phone.errors}}
                </div> 
            </div><!--End first row-->
            <div class="row">
                <div class="form-group col-3 mb-0">
                    <label>역할</label>
                    {% render_field form.role placeholder="역할" class+="form-control" %}
                    {{form.phone.errors}}
                </div>
                <div class="form-group col-3 mb-0 py-4">
                    <label>현재활동</label>
                    {% render_field form.is_active%}
                </div>
            </div><!--End second row-->
        </div><!--End card-body-->

        <div class="card-footer">
        <button type="submit" class="btn btn-outline-warning">업데이트</button>
        <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-outline-primary">뒤로가기</a>
        </div>
    </form>
</div><!--End card-->
</div>
{% endblock content %}

templates/storeman/customer/edit_customer_address.html
{% extends '../admin_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container p-2">
    <div class="card">
        <div class="card-header">
            <h5>배송지수정</h5>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-3">
                        {{form.nick_name|as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.h_name|as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.e_name|as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.biz_type|as_crispy_field}}
                    </div>
                </div><!--first row-->
                <div class="row">
                    <div class="col-md-5">
                        {{form.address|as_crispy_field}}
                    </div>
                    <div class="col-md-2">
                        {{form.state|as_crispy_field}}
                    </div>
                    <div class="col-md-2">
                        {{form.city|as_crispy_field}}
                    </div>
                    <div class="col-md-2">
                        {{form.postcode|as_crispy_field}}
                    </div>
                </div><!--Second row-->
                <div class="row">
                    <div class="col-md-3">
                        {{form.driver|as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.vegi_code|as_crispy_field}}
                    </div>
                    <div class="col-md-3">
                        {{form.gen_code|as_crispy_field}}
                    </div>
                    <div class="col-md-3 p-4">
                        {{form.default|as_crispy_field}}
                    </div>
                </div><!--Third row-->
                <div class="row">
                    <div class="col-md-3">
                        {{form.delivery_instructions|as_crispy_field}}
                    </div>
                </div><!--Forth row-->
                <div class="card-footer">
                    <button type="submit" class="btn btn-warning">저장하기</button>
                    <a href="{% url "storeman:display_customer_details" customer.id %}" class="btn btn-primary">뒤로가기</a>
                    <a href="#delModal" roll="button" data-bs-toggle="modal" class="btn btn-danger float-end"><i class="bi bi-trash3"></i></a>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Delete Customer address Modal HTML -->
<div id="delModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h6class="modal-title">확인</h6>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p> 배송지 {{address.address}} 삭제하겠습니까?</p>
                <p class="text-secondary"><small></small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">나가기</button>
                <a href="{% url 'storeman:delete_customer_address' customer.id address.id %}"><button type="button"
                    class="btn btn-primary">삭제하기</button></a>
                </div>
            </div>
        </div>
</div>
<!--End Modal-->
{% endblock content %}