company/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "company"

urlpatterns = [
    # My information
    path("my_dashboard/", views.my_dashboard, name="my_dashboard"),
    path("my_address/", views.my_addressbook, name="my_addressbook"),
    # path("add_address", views.add_address, name="add_address"),
    path("my_address/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("my_address/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("my_address/set_default/<slug:id>/", views.set_default, name="set_default"),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, cart, checkout, order

app_name = "store"

urlpatterns = [
    # path("", views.home, name="home"),
    path("", cart.wishlist_view, name="home"),
    # path("", views.category, name="home"),
    path("category/", views.category, name="category"),
    path("product/<str:slug>", views.product_list, name="product_list"),
    path(
        "product/<str:cat_slug>/<str:prd_id>",
        views.product_detail,
        name="product_detail",
    ),
    # 제품검색
    # path("search", views.search_ajax),
    # path("searchproducts", views.searchproducts, name="searchproducts"),
    path("search/", views.search, name="search"),
    # Cart
    path("add-to-cart", cart.addtocart, name="addtocart"),
    path("cart", cart.viewcart, name="cart"),
    path("update-cart", cart.updatecart, name="updatecart"),
    path("delete-cart-item", cart.deletecartitem, name="deletecartitem"),
    # 주문
    path("checkout", checkout.index, name="checkout"),
    path("place-order", checkout.place_order, name="place_order"),
    # 주문상세내역
    path("my-orders", order.my_orders, name="myorders"),
    path("order-view/<str:tk_no>", order.order_view, name="orderview"),
    path("my-orders/<str:tk_no>", order.order_cancel, name="order_cancel"),
    # path("export_csv/<str:tk_no>", order.export_csv, name="export_csv"),
    # path("export_pdf/<str:tk_no>", order.export_pdf, name="export_pdf"),
    # 자주주문내역
    path("wish_list", cart.wishlist_view, name="wishlist_view"),
    path("add_to_wishlist", cart.add_to_wishlist, name="add_to_wishlist"),
    path("delete_wish_item", cart.delete_wishitem, name="delete_wishitem"),
    path("add_wish_to_cart", cart.add_wish_to_cart, name="add_wish_to_cart"),
    # Language code
    # path('/language/<str:language_code>', views.set_language, name='set_language'),
]

templates/myinfo/add_address.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="py-3 mt-3">
    <div class="container">
        <a class="text-black" href="{% url 'store:home' %}">홈 /</a>
        <a class="text-black" href="{% url 'store:myorders' %}">나의주문내역</a>
    </div>
</div>
<main class="container my-4">
    <h3 class="my-4 border-bottom pb-1">배송지등록/수정</h3>
    {% if msg %}
    <p class="text-success">{{ msg }}</p>
    {% endif %}
    <table class="table table-bordered">
        <form method="post">
            {% csrf_token %}
            {{form.as_table}}
            <tr>
                <td colspan="2">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </td>
            </tr>
        </form>
    </table>
</main>
{% endblock content %}

templates/myinfo/myinfo_addressbook.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="container">
<section class="bg-light p-3">
    <h3 class="boarder-bottom pb-3">{{_("Manage address book")}}</h3>
        <div class="table-responsive" id="no-more-tables">
                <table class="table bg-white text-center">
                    <thead class="bg-info">
                        <tr>
                            <th>{{_("Company name")}}</th>
                            <th>{{_("Company branch")}}</th>
                            <th>{{_("Address")}}</th>
                            <th>{{_("Status")}}</th>
                            <th>{{_("Apply")}}</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for addr in address %}
                        <tr class="{% if addr.default %} table-warning {% endif %}">
                            <td data-title="상호">{{addr.e_name}}</td>
                            <td data-title="점포">{{addr.nick_name}}</td>
                            <td data-title="주소">{{addr.address}},{{addr.city}}</td>
                            <td data-title="상태">
                                {% if addr.default %}
                                <p class="bg-warning bg-">{{_("Default address")}}</p>
                                {% endif %}
                            </td>
                            <td data-title="선택">
                                <a class="p-1 addr_id" href="{% url 'company:set_default' addr.id %}">
                                    <button type="button" class="btn btn-sm btn-primary selectAddrBtn">
                                        {{_("Apply")}}</button></a>
                                    </td>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
</section> 
</div>
{% endblock content %}

templates/myinfo/myorders.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
  <div class="container">
            <div class="cartdata table-responsive" id="no-more-tables">
                <table class="table bg-white">
                    <thead class="bg-light text-dark">
                        <tr>
                            <th>#</th>
                            <th>{{_('Date')}}</th>
                            <th>{{_('Number')}}</th>
                            <th>{{_('Status')}}</th>
                            <th>{{_('View')}}</th>
                        </tr>
                    </thead>
                    <tbody class="product_data carddata">
                        {% for item in orders %}
                        <tr>
                            <td data-title="#">{{forloop.counter}}</td>
                            <td data-title="{{_('Date')}}">{{ item.created_at|date:"Y/m/d"}}</td>
                            <td data-title="{{_('Number')}}">{{ item.tracking_no}}</td>
                            <td data-title="{{_('Status')}}">{{ item.status}}</td>
                            <td data-title="{{_('View')}}">
                                <div class="product_data">
                                        <a href="{% url 'store:orderview' item.tracking_no %}" class="btn btn-outline-primary">{{_('Detail')}}</a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
    </div>



{% endblock content %}

templates/myinfo/order_details.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow">
                <div class="card-header d-flex justify-content-between ">
                    <h4 class="mt-2">{{_('Order Number')}} : {{order.tracking_no}}</h4>
                    <a href="{% url 'store:myorders' %}" class="btn btn-info btn-sm float-end">{{_('Go Back')}}</a>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 mt-2">
                            <h4><i class="fa-solid fa-truck-fast"></i> {{_("Delivery To")}}</h4>
                            <hr>
                            <ul class="text-uppercase">
                                <li>{{order.company_e_name}}<li>
                                <li>{{ order.address}}</li>
                                <li>{{ order.city}}
                                <li>{{ order.state}}, {{ order.postcode}}</li>
                                <li>T: {{ order.phone}}</li>
                            </ul>
                            <ul>
                                <li><strong>{{_('E-mail')}}:</strong> {{ order.email}}</li>
                                <li><strong>{{_('Order Status')}}:</strong> {% if order.status == "Pendding" %}{% endif %} <a class="badge bg-primary text-wrap">{{order.status}}</a></li>
                                <li class="fw-bold">{{_('Messages')}}: {{order.message}}</li>
                            </ul>
                        </div>
                        <div class="col-md-6 mt-2">
                            <h4><i class="fas fa-shopping-cart"></i> {{_('Purchase Order')}}</h4>
                            <hr>
                            <table class="table table-bordered table-responsive text-start">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{{_('Product')}}</th>
                                        <th>{{_('Qty')}}</th>
                                        <th>{{_('Spec')}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in orderitems %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td>{{item.product.title}}({{item.product.e_title}})</td>
                                        <td>{{item.quantity}}</td>
                                        <td>{{item.product.spec}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% if order.status == "Pending" %}
                            <div class="text-end">
                                <a href="#myModal" roll="button" class="btn btn-sm btn-danger" data-bs-toggle="modal">{{_('Order Cancel')}}</a>
                            </div>
                            {% endif %}
                             <!-- Modal HTML -->
    <div id="myModal" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h6 class="modal-title">{{_('Confirmation')}}</h6>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <p>{{_('Do you want to delete this order number?')}}</p>
                    <p class="text-secondary"><small></small></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{_('Cancel')}}</button>
                    <a href="{% url 'store:order_cancel' order.tracking_no %}"><button type="button" class="btn btn-primary">{{_('Delete')}}</button></a>
                </div>
            </div>
        </div>
    </div>
    <!--End Modal-->
                        </div>  
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



{% endblock content %}