company/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "company"

urlpatterns = [
    # My information
    path("my_dashboard/", views.my_dashboard, name="my_dashboard"),
    path("my_address/", views.my_addressbook, name="my_addressbook"),
    # path("add_address", views.add_address, name="add_address"),
    path("my_address/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("my_address/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("my_address/set_default/<slug:id>/", views.set_default, name="set_default"),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, cart, checkout, order

app_name = "store"

urlpatterns = [
    # path("", views.home, name="home"),
    path("", cart.wishlist_view, name="home"),
    # path("", views.category, name="home"),
    path("category/", views.category, name="category"),
    path("product/<str:slug>", views.product_list, name="product_list"),
    path(
        "product/<str:cat_slug>/<str:prd_id>",
        views.product_detail,
        name="product_detail",
    ),
    # 제품검색
    # path("search", views.search_ajax),
    # path("searchproducts", views.searchproducts, name="searchproducts"),
    path("search/", views.search, name="search"),
    # Cart
    path("add-to-cart", cart.addtocart, name="addtocart"),
    path("cart", cart.viewcart, name="cart"),
    path("update-cart", cart.updatecart, name="updatecart"),
    path("delete-cart-item", cart.deletecartitem, name="deletecartitem"),
    # 주문
    path("checkout", checkout.index, name="checkout"),
    path("place-order", checkout.place_order, name="place_order"),
    # 주문상세내역
    path("my-orders", order.my_orders, name="myorders"),
    path("order-view/<str:tk_no>", order.order_view, name="orderview"),
    path("my-orders/<str:tk_no>", order.order_cancel, name="order_cancel"),
    # path("export_csv/<str:tk_no>", order.export_csv, name="export_csv"),
    # path("export_pdf/<str:tk_no>", order.export_pdf, name="export_pdf"),
    # 자주주문내역
    path("wish_list", cart.wishlist_view, name="wishlist_view"),
    path("add_to_wishlist", cart.add_to_wishlist, name="add_to_wishlist"),
    path("delete_wish_item", cart.delete_wishitem, name="delete_wishitem"),
    path("add_wish_to_cart", cart.add_wish_to_cart, name="add_wish_to_cart"),
    # Language code
    # path('/language/<str:language_code>', views.set_language, name='set_language'),
]

storeman/urls.py
from django.contrib import admin
from django.urls import path
from .views import (
    admin_home,
    export_csv,
    export_pdf,
)
from .product_man import (
    product_list,
    create_product,
    display_product_detail,
    edit_product,
    delete_product,
)
from .address_man import (
    create_customer_address,
    edit_customer_address,
    delete_customer_address,
)
from .customer_man import (
    display_customer_list,
    display_customer_details,
    create_customer,
    edit_customer,
    delete_customer,
)

from .order_man import (
    order_list,
    create_order,
    order_details,
    submit_order,
    daily_order,
    order_list_detail,
)

from .staff_man import (
    display_staff,
    create_staff,
    create_driver,
    edit_staff,
)

from .delivery_man import (
    display_delivery_team,
    edit_delivery_team,
)

app_name = "storeman"

urlpatterns = [
    # Order
    path("", admin_home, name="admin_home"),
    path("order_list/", order_list, name="order_list"),
    path("order_list_detail/<str:pk_id>", order_list_detail, name="order_list_detail"),
    path("daily_order/", daily_order, name="daily_order"),
    path("submit_order/", submit_order, name="submit_order"),
    path("create_order/", create_order, name="create_order"),
    path("order_details/<str:tk_no>", order_details, name="order_details"),
    path("export_csv/<str:tk_no>", export_csv, name="export_csv"),
    path("export_pdf/<str:tk_no>", export_pdf, name="export_pdf"),
    path("display_customer_list/", display_customer_list, name="display_customer_list"),
    path(
        "display_customer_details/<str:pk_id>",
        display_customer_details,
        name="display_customer_details",
    ),
    path(
        "create_customer_address/<str:pk_id>",
        create_customer_address,
        name="create_customer_address",
    ),
    path(
        "edit_customer_address/<str:pk_id>/<str:addr_id>",
        edit_customer_address,
        name="edit_customer_address",
    ),
    path(
        "delete_customer_address/<str:pk_id>/<str:addr_id>",
        delete_customer_address,
        name="delete_customer_address",
    ),
    path("create_customer/", create_customer, name="create_customer"),
    path("edit_customer/<str:pk_id>", edit_customer, name="edit_customer"),
    path("delete_customer/<str:pk_id>", delete_customer, name="delete_customer"),
    path("submit_order/", submit_order, name="submit_order"),
    # Product
    path("create_product/", create_product, name="create_product"),
    path("product_list/", product_list, name="product_list"),
    path(
        "display_product_detail/<str:pk_id>",
        display_product_detail,
        name="display_product_detail",
    ),
    path("edit_product/<str:pk_id>", edit_product, name="edit_product"),
    path("delete_product/<str:pk_id>", delete_product, name="delete_product"),
    # Staff
    path("display_staff/", display_staff, name="display_staff"),
    path("create_staff/", create_staff, name="create_staff"),
    path("edit_staff/<str:pk_id>", edit_staff, name="edit_staff"),
    path("create_driver/<str:pk_id>", create_driver, name="create_driver"),
    # Delivery
    path("display_delivery_team/", display_delivery_team, name="display_delivery_team"),
    path(
        "edit_delivery_tean/<str:pk_id>", edit_delivery_team, name="edit_delivery_team"
    ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>{% block title %}Gomaps Order system{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--bootstrap-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <!--bootstrap Icon-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <!--Google Fonts-->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
  <!--fontawesome Free version-->
  <script src="https://kit.fontawesome.com/33e8dad915.js" crossorigin="anonymous"></script>
  <!--JqueryUI for search function-->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  <!--Custom CSS-->
  <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
  <!-- Alertify CSS -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
  <!-- Alertify Default theme -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css" />
  <link rel="icon" href="/media/images/gomaps.png">


   <!--JQuery-->
   <script src="{% static 'js/jquery.js' %}"></script>
   <script src="{% static 'js/custom.js' %}"></script>
   <!--JqueryUI-->
   <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
     <!--WAYPOINT-->
   <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
   <script src="/static/js/infinite.min.js"></script>

</head>

<body>
  {% include "./navbar.html" %}
  {% load i18n %}
  {% block content %}
  {% endblock content %}


 <!--bootstrap Popper JS-->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz"
    crossorigin="anonymous"></script>

<!--Search script-->
  <script>
    var availableTags = [];
    $.ajax({
      method: "GET",
      url: "/search",
      success: function (response) {
        startAutocomplete(response);
      }
    });

    function startAutocomplete(availableTags)
     {
      $("#searchproducts").autocomplete({
        source: availableTags
      });
    }
  </script>

  <!--Alertify-->
  <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
  <script>
    alertify.set('notifier', 'position', 'top-center');
    {% for msg in messages %}
    alertify.success('{{ msg }}');
    {% endfor %}
  </script>
</body>
</html>

templates/message.html
{% for message in messages %}
  <div class="toast notification bg-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}" role="alert" aria-live="assertive" aria-atomic="true" data-delay="10000">
    <div class="toast-header">
      <strong class="mr-auto">
        {% if message.tags == 'error' %}
        {% elif message.tags == 'warning' %}
        {% elif message.tags == 'info' %}
        {% elif message.tags == 'success' %}
        {% endif %}
        {{message.tags|capfirst}}
      </strong>
      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="toast-body">
      {{message|safe}}
    </div>
  </div>
{% endfor %}

templates/navbar.html
{% load i18n %}
<nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color:#2d2d2d">
  <div class="container">
    <div class="d-flex">
    <a class="navbar-brand" href="/"><img src="/media/images/gomaps.png" alt="" style="height: 30px;"></a>
          <!--Start search-->
          <form method="get" action="{% url 'store:search' %}">
            <div class="col-sm-12 py-2">
              <div class="input-group me-auto">
                <input name="q" type="text" required class="form-control ms-2" placeholder="{{_('Search...')}}" value={{ q|default_if_none:'' }}>
                <button type="submit" class="input-group-text"><i class="bi bi-search"></i></button>
              </div>
            </div>
          </form>
          <!--End Search-->
    <!--Hamburger button-->
    <button class="navbar-toggler ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"  
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>
  <!--End Button-->
    <div class="collapse navbar-collapse" id="navbarNav">
         <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            {{ _('Categories') }}
          </a>
          <ul class="dropdown-menu">
            {% for c in categories %}
            <li><a class="dropdown-item" href="{% url 'store:product_list' c.slug %}">{{c.title}}({{c.e_title}})</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item add_wish">
          <a class="nav-link active" aria-current="page" href="{% url 'store:wishlist_view' %}"><i
            class="fas text-light fa-star"></i> {{ _('Favorite') }}</a>
        </li>
        <li class="nav-item del_cart add_data">
          <a class="nav-link active" aria-current="page" href="{% url 'store:cart' %}"><i class="fas text-light fa-shopping-cart"></i> {{ _('Cart') }} 
            <div id="product_qty" class="d-inline-flex text-warning">
              ({{cart|length}})
            </div>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            <i class="fa-regular fa-circle-user"></i> {{request.user.username}}</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'store:myorders' %}">{{ _('Order History')}}</a></li>
            <li><a class="dropdown-item" href="{% url 'company:my_addressbook' %}" disable>{{ _('Choose location')}}</a></li>
            <li><a class="dropdown-item" href="{% url 'account_logout' %}">{{_('Logout')}}</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">{{_('Login')}}</a>
        </li>
        {% endif %}
        {% if request.user.is_superuser%}
        </li> 
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'storeman:admin_home' %}">{{_('Admin')}}
            <i class="bi bi-shield-exclamation"></i>
          </a>
        </li>
        {% endif %}
</ul>
    </div>
  </div>
</nav>
<!--Sub Menu-->
<div class="py-3 mt-1">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <a class="text-black" href="{% url 'store:category' %}">{{ _('Categories') }} |</a>
      <a class="text-black"  href="{% url 'store:wishlist_view' %}">{{_('Favorite')}} |</a>
      <a class="text-black" href="{% url 'store:cart'%}">{{_('Cart')}}</a>
    </div>
    </div>
    </div>
</div>

templates/pagination.html
{% load filter_tags %}

<nav aria-label="Page navigation">
  {% if page_obj.has_other_pages %}
    <ul class="pagination justify-content-center">    
    
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">&laquo 앞쪽</a>
    </li>
    {% else %}
    <li class="page-item"><span class="page-link" >처음</span></li>
    {% endif %}
  
    {% for page in custom_range%}
      {% if page == page_obj.number %}
      <li class="page-item active" aria-current="page">
        <a class="page-link" style="text-decoration:none; color:red;" href="?{% param_replace page=page %}">{{page}}</a>
      </li>
      {% else %}     
      <li class="page-item">
        <a class="page-link" style="text-decoration:none; color:blue;" href="?{% param_replace page=page %}">{{page}}</a>
      </li>
      {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">다음</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?{% param_replace page=page_obj.paginator.num_pages %}">마지막 &raquo</a>
      </li>
    {% endif %}
  </ul>
  {% endif %}
</nav>

templates/pagination_large.html
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">« Previous page</a>

  {% if page_obj.number > 3 %}
    <a href="?page=1">1</a>
    {% if page_obj.number > 4 %}
      <span>...</span>
    {% endif %}
  {% endif %}
{% endif %}

{% for num in page_obj.paginator.page_range %}
  {% if page_obj.number == num %}
    <a href="?page={{ num }}">{{ num }}</a>
  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a href="?page={{ num }}">{{ num }}</a>
  {% endif %}
{% endfor %}

{% if page_obj.has_next %}
  {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
    <span>...</span>
    <a href="?page={{ page_obj.paginator.num_pages }}{{product_filter.title}}">{{ page_obj.paginator.num_pages }}</a>
  {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
    <a href="?page={{ page_obj.paginator.num_pages }}{{product_filter.title}}">{{ page_obj.paginator.num_pages }}</a>
  {% endif %}

  <a href="?page={{ page_obj.next_page_number }}{{product_filter.title}}">Next Page »</a>
{% endif %}