company/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "company"

urlpatterns = [
    # My information
    path("my_dashboard/", views.my_dashboard, name="my_dashboard"),
    path("my_address/", views.my_addressbook, name="my_addressbook"),
    # path("add_address", views.add_address, name="add_address"),
    path("my_address/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("my_address/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("my_address/set_default/<slug:id>/", views.set_default, name="set_default"),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, cart, checkout, order

app_name = "store"

urlpatterns = [
    # path("", views.home, name="home"),
    path("", cart.wishlist_view, name="home"),
    # path("", views.category, name="home"),
    path("category/", views.category, name="category"),
    path("product/<str:slug>", views.product_list, name="product_list"),
    path(
        "product/<str:cat_slug>/<str:prd_id>",
        views.product_detail,
        name="product_detail",
    ),
    # 제품검색
    # path("search", views.search_ajax),
    # path("searchproducts", views.searchproducts, name="searchproducts"),
    path("search/", views.search, name="search"),
    # Cart
    path("add-to-cart", cart.addtocart, name="addtocart"),
    path("cart", cart.viewcart, name="cart"),
    path("update-cart", cart.updatecart, name="updatecart"),
    path("delete-cart-item", cart.deletecartitem, name="deletecartitem"),
    # 주문
    path("checkout", checkout.index, name="checkout"),
    path("place-order", checkout.place_order, name="place_order"),
    # 주문상세내역
    path("my-orders", order.my_orders, name="myorders"),
    path("order-view/<str:tk_no>", order.order_view, name="orderview"),
    path("my-orders/<str:tk_no>", order.order_cancel, name="order_cancel"),
    # path("export_csv/<str:tk_no>", order.export_csv, name="export_csv"),
    # path("export_pdf/<str:tk_no>", order.export_pdf, name="export_pdf"),
    # 자주주문내역
    path("wish_list", cart.wishlist_view, name="wishlist_view"),
    path("add_to_wishlist", cart.add_to_wishlist, name="add_to_wishlist"),
    path("delete_wish_item", cart.delete_wishitem, name="delete_wishitem"),
    path("add_wish_to_cart", cart.add_wish_to_cart, name="add_wish_to_cart"),
    # Language code
    # path('/language/<str:language_code>', views.set_language, name='set_language'),
]

store/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.urls import reverse
from customer.models import User
from company.models import AddressBook
from django.core.files import File


import barcode
from barcode.writer import ImageWriter
from io import BytesIO


class Category(models.Model):
    title = models.CharField(_("Title"), max_length=100, unique=True, null=True)
    e_title = models.CharField(_("e_title"), max_length=100, null=True)
    slug = models.SlugField(_("Slug"), max_length=100, unique=True, allow_unicode=True)
    image = models.ImageField(
        _("Image"),
        upload_to="images/category",
        default="images/category/default.png",
        blank=True,
    )
    is_active = models.BooleanField(_("Is Active"), default=True)

    class Meta:
        ordering = ("title",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return f"{self.title}"


class Product(models.Model):
    title = models.CharField(_("Title"), max_length=200)
    e_title = models.CharField(
        _("English Title"), max_length=100, null=True, blank=True
    )
    # slug = models.SlugField(max_length=100, unique=True, allow_unicode=True)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    bar_code = models.CharField(_("BAR Code"), max_length=6, blank=True, null=True)
    location = models.CharField(_("Location"), max_length=6, blank=True, null=True)
    list_price = models.DecimalField(
        _("List Price"), max_digits=10, decimal_places=2, blank=True, null=True
    )
    sale_price = models.DecimalField(
        _("Sale Price"), max_digits=10, decimal_places=2, blank=True, null=True
    )
    quantity = models.IntegerField(_("Quantity"), null=True, blank=True)
    description = models.TextField(_("Description"), blank=True, null=True)
    brand = models.CharField(_("Brand"), max_length=100, null=True, blank=True)
    unit = models.CharField(_("Unit"), max_length=20, null=True, blank=True)
    spec = models.CharField(_("Spec"), max_length=20, null=True, blank=True)
    color = models.CharField(_("Color"), max_length=10, null=True, blank=True)
    per_box = models.IntegerField(_("Per Box"), null=True, blank=True)
    tag = models.CharField(_("Tag"), max_length=150, null=True, blank=True)

    image = models.ImageField(
        _("Image"),
        upload_to="images/product",
        default="images/product/default.png",
        blank=True,
    )
    is_active = models.BooleanField(_("Is Active"), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["location"]
        verbose_name_plural = "Products"
        index_together = [["id", "title"]]

    def __str__(self):
        return f"{self.title}"


class OrderCode(models.Model):

    order_key = (
        ("일반", "일반"),
        ("야채", "야채"),
        ("주류", "주류"),
    )
    code = models.CharField(max_length=6, unique=True, null=True, blank=True)
    order_type = models.CharField(max_length=10, choices=order_key, default="일반")
    address = models.ForeignKey(
        AddressBook, on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return f"{self.code},{self.address},{self.order_type}"


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_qty = models.IntegerField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    order_code = models.CharField(max_length=6, null=True, blank=True)


class Order(models.Model):
    aus_state = (
        ("NSW", "NSW"),
        ("VIC", "VIC"),
        ("QLD", "QLD"),
        ("ACT", "ACT"),
        ("SA", "SA"),
        ("WA", "WA"),
        ("NT", "NT"),
        ("TAS", "TAS"),
    )

    order_status = (
        ("Pending", "Pending"),
        ("Out for delivery", "Out for delivery"),
        ("Delivered", "Delivered"),
    )
    PAYMENT = (
        ("수금", "수금"),
        ("미수금", "미수금"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=150, null=False)
    company_e_name = models.CharField(max_length=150, blank=True, null=True)
    fname = models.CharField(max_length=150, null=False)
    lname = models.CharField(max_length=150, null=False)
    phone = models.CharField(max_length=10, null=False)
    email = models.CharField(max_length=150, null=False)
    address = models.TextField(null=False)
    city = models.CharField(max_length=100, null=False)
    state = models.CharField(max_length=3, choices=aus_state, default="NSW")
    postcode = models.CharField(max_length=4, null=False)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    payment_mode = models.CharField(max_length=150, choices=PAYMENT, null=True)
    payment_id = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(max_length=150, choices=order_status, default="Pending")
    message = models.TextField(null=True, blank=True)
    tracking_no = models.CharField(max_length=50, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    barcode_img = models.ImageField(upload_to="order/barcode/%Y/%m/%d/", blank=True)
    ami_file = models.FileField(upload_to="order/ami/%Y/%m/%d/", blank=True)
    ami_daily_file = models.FileField(upload_to="order/daily/", blank=True)
    order_pdf = models.FileField(upload_to="order/pdf/%Y/%m/%d/", blank=True)
    pdf_daily_file = models.FileField(upload_to="order/daily", blank=True)
    driver = models.CharField(max_length=100, blank=True)
    driver_first_name = models.CharField(max_length=50, blank=True)
    driver_last_name = models.CharField(max_length=50, blank=True)
    driver_team = models.CharField(max_length=100, blank=True)
    delivery_note = models.TextField(null=True, blank=True)
    delivery_photo = models.ImageField(
        verbose_name="첨부사진", upload_to="order/delivery/%Y/%m/%d", blank=True
    )

    def __str__(self):
        return f"{self.id}, {self.tracking_no},{self.barcode_img}"

    def delete(self, *args, **kwargs):
        self.barcode_img.delete()
        self.ami_file.delete()
        self.order_pdf.delete()
        super().delete(*args, **kwargs)

    class Meta:
        ordering = ["-created_at"]


class OrderItem(models.Model):
    STATUS = (
        ("정상", "정상"),
        ("반품", "반품"),
        ("미배달", "미배달"),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(null=False)
    order_code = models.CharField(max_length=6, null=True, blank=True)
    order_type = models.CharField(max_length=10, null=True, blank=True)
    item_status = models.CharField(
        max_length=100, null=True, blank=True, choices=STATUS, default="정상"
    )
    # 제품위치별 정렬
    class Meta:
        ordering = ["product"]

    def __str__(self):
        return f"{self.order.id}"

    # 주문한 갯수 x 제품가격
    def get_item_price(self):
        return self.price * self.quantity


# Wishlist (자주주문제품)


class WishItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user}"


# Daily Order 처리


class DailyJobs(models.Model):
    created_user = models.ForeignKey(
        User, verbose_name=_("작성자"), on_delete=models.CASCADE, null=True
    )
    daily_merged_csv = models.FileField(
        verbose_name=_("알맹이CSV"), upload_to="order/daily/csv/%Y/%m/%d/", blank=True
    )
    daily_merged_pdf = models.FileField(
        verbose_name=_("주문서PDF"), upload_to="order/daily/pdf/%Y/%m/%d", blank=True
    )
    created_at = models.DateTimeField(verbose_name=_("작성일"), auto_now_add=True)

    def __str__(self):
        return f"{self.created_user}"

store/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "delivery_note",
        ]

store/views.py
# from django.utils import translation
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.db.models import Q
from .models import *

# Import Pagination Stuff
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# def set_language(request, language_code):
#     translation.activate(language_code)
#     request.session[translation.LANGUAGE_SESSION_KEY] = language_code
#     return HttpResponse(status=200)


@login_required(login_url="account_login")
def home(request):
    if request.user.is_superuser:
        return redirect("/storeman")
    if request.user.is_staff and request.user.role == "DRIVER":
        return redirect("/delivery")
    else:

        category = Category.objects.all()
        context = {"category": category, "next": next}
        return render(request, "store/home.html", context)


@login_required(login_url="account_login")
def category(request):
    category = Category.objects.all()
    context = {"category": category}
    return render(request, "store/category.html", context)


@login_required(login_url="account_login")
def product_list(request, slug):
    if Category.objects.filter(slug=slug):
        products = Product.objects.filter(category__slug=slug, is_active=True)
        category = Category.objects.filter(slug=slug).first()
        context = {
            "products": products,
            "category": category,
        }
        return render(request, "store/product_list.html", context)
    else:
        messages.warning(request, "No such category found")
        return redirect("category")


@login_required(login_url="account_login")
def product_detail(request, cat_slug, prd_id):
    if Category.objects.filter(slug=cat_slug):
        if Product.objects.filter(id=prd_id, is_active=True):
            products = Product.objects.filter(id=prd_id, is_active=True).first()
            context = {"products": products}
        else:
            messages.error(request, "No such Category found")
            return redirect("category")
    else:
        messages.error(request, "No such Category found")
        return redirect("category")
    return render(request, "store/product_detail.html", context)


# @login_required(login_url="account_login")
# def search_ajax(request):
#     h_products = Product.objects.filter(is_active=True).values_list("title", flat=True)
#     e_products = Product.objects.filter(is_active=True).values_list(
#         "e_title", flat=True
#     )
#     h_products_list = list(h_products)
#     e_products_list = list(e_products)
#     plus_product = h_products_list + e_products_list
#     products_list = list(filter(None, plus_product))  # list 안에 빈 값지우기
#     return JsonResponse(products_list, safe=False)


# @login_required(login_url="account_login")
# def searchproducts(request):
#     if request.method == "POST":
#         searchedterm = request.POST.get("productsearch")
#         if searchedterm == "":
#             return redirect(request.META.get("HTTP_REFERER"))
#         else:
#             product = (
#                 Product.objects.filter(title__icontains=searchedterm)
#                 | Product.objects.filter(e_title__icontains=searchedterm)
#             ).first()
#             if product:
#                 return redirect(
#                     "product/" + product.category.slug + "/" + str(product.id)
#                 )
#             else:
#                 messages.info(request, "찾는 제품이없습니다.")
#                 return redirect(request.META.get("HTTP_REFERER"))
#     return redirect(request.META.get("HTTP_REFERER"))


@login_required(login_url="account_login")
def search(request):
    q = request.GET.get("q", "")
    data = Product.objects.filter(title__icontains=q) | Product.objects.filter(
        e_title__icontains=q
    )
    context = {
        "search_data": data,
    }
    return render(request, "store/search.html", context)

templates/store/cart.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<div class="container">
    <section class="bg-light p-3">
        <h3 class="text-center pb-3">{{ _('Purchase Order') }}</h3>
            {% for addr in address %}
                {% if addr.default == True %}
            <p class="text-start">[ {{_('Delivery to')}}: <strong>{{addr.e_name}}-{{addr.address}},{{addr.city}}</strong> ]</p>
                {% endif %}
            {% endfor %}
            <div class="cartdata table-responsive" id="no-more-tables">
                <table class="table bg-white carddata">
                    <thead class="bg-success text-light">
                        <tr>
                            <th>#</th>
                            <th>{{_('Product')}}</th>
                            <th>{{_('Spec')}}</th>
                            <th>{{_('Unit')}}</th>
                            <th>{{_('Qty')}}</th>
                            <th>{{_('Delete')}}</th>
                        </tr>
                    </thead>
                    <tbody class="product_data carddata">
                        {% for item in cart %}
                        <tr>
                            <td data-title="#">{{forloop.counter}}</td>
                            <td data-title="Product">{{item.product.title}}<br><small>{{item.product.e_title}}</small></td>
                            <td data-title="Spec">{{item.product.spec}}</td>
                            <td data-title="Unit">{{item.product.unit}}</td>
                            <td data-title="Qty">
                                <div class="product_data">
                                    <input type="hidden" class="prod_id" value="{{ item.product.id }}">
                                    {% csrf_token %}
                                    <div class="imput-group text-center mb-3 d-flex flex-nowrap" style="width:130px; height:25px;">
                                        <button class="input-group-text changeQuantity decrement-btn">-</button>
                                        <input type="text" name="quantity" class="form-control qty-input text-center" style="font-size:0.9rem"
                                            value="{{item.product_qty}}">
                                        <button class="input-group-text changeQuantity increment-btn">+</button>
                                    </div>
                                </div>
                            </td>
                            <td data-title="Delete">
                                <input type="hidden" class="prod_id" value="{{ item.product.id }}">
                                {% csrf_token %}
                                <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#cartModal">
                                    {{_('Delete')}} <i class="bi bi-trash"></i></button>
                            </td>
                        </tr>
                     <!-- Modal HTML -->
                     <div id="cartModal" class="modal fade" tabindex="-1">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h6 class="modal-title">{{_('Confirmation')}}</h6>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                </div>
                                <div class="modal-body">
                                    <p>{{_('Do you want to delete this item?')}}</p>
                                    <p class="text-secondary"><small></small></p>
                                </div>
                                <div class="modal-footer product_data">
                                    <input type="hidden" class="prod_id" value="{{ item.product.id }}">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{_('Cancel')}}</button>
                                   <button type="button" class="btn btn-danger delete-cart-item">{{_('Delete')}}</button>
                                </div>
                            </div>
                        </div>
                     </div>
                     <!--End Modal--> 

                        {% endfor %}
                    </tbody>
                </table>
                {% if cart|length > 0 %}
                <a href="{% url 'store:checkout' %}" class="btn btn-outline-success float-end">{{_('Proceed to Order')}}</a>
                {% endif %}
            </div>
        </section>
    </div>
{% endblock content %}

templates/store/category.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3 infinite-container">
        {% for c in categories %}
        <div class="col-6 col-md-4">
            <div class="card h-100 shadow-sm">

                <a href="{% url 'store:product_list' c.slug %}">
                    <div class="card-body">
                        <div class="category-image">
                            <img src="{{c.image.url}}" alt="category image" class="w-100 card-img-top">
                        </div>
                        <h4 class="text-center">{{c.title}}</h4>
                        <h4 class="text-center">{{c.e_title}}</h4>

                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

<!--
{% if c.title == "야채" %}
<div class="alert alert-danger" role="alert">
<h5 class="text-center">야채 주문은 <strong>오후 5시전</strong>까지만 받습니다.</h5>
</div>
{% endif %}
-->

templates/store/checkout.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-7">
            <div class="card shadow">
                <div class="card-body">
                    <i class="fa-solid fa-truck-fast"></i> </h5>{{_(' Delivery to')}}: {{company.h_name}}({{company.e_name}}) <span class="text-primary">{{company.address}}, {{company.city}}</span></h5>
                    <hr>
                    <p>{% trans 'Choose your location' %}</p>
                    <div class="row">
                        {% for addr in addressbook %}
                        <div class="col-6 col-md-auto">
                        <div class='card me-1 mt-2 {% if addr.default %}shadow bg-warning bg-opacity-10 {% else %} text-muted {% endif %}' style="width:140px;"> 
                            <div class="card-body">
                                <div class="card-title">{{addr.e_name}}</div>
                                <div class="card-text" style="font-size:0.8rem;">{{addr.nick_name}}
                                    <br>
                                    {{addr.address}},{{addr.city}}
                                    {% if addr.default %}
                                    <p class="text-bg-danger text-danger text-center">{{_('Default Address')}}</p>
                                    <div class="card-footer d-flex justify-content-center bg-opacity-10">
                                    <i class="fa-regular fa-circle-check fa-2x text-danger"></i> 
                                    </div>
                                    {% else %}
                                    <div class="card-footer bg-white d-flex justify-content-center">
                                    <a href="{% url 'company:set_default' addr.id %}">
                                    <i class="fa-regular fa-hand-pointer"></i> {{_('Select')}}
                                    </a>
                                    </div>                                              
                                    {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                            {% endfor %}
                        </div>
                    </div>
                <div class="p-2">
<form action="{% url 'store:place_order' %}" method="POST">
                            {% csrf_token %}
                            <div class="col-md-12 mt-2">
                                <P><strong>{{_('Do you have a message')}}?</strong>
                                    <P>
                                        <textarea type='text' value="{{ message }}" class='form-control' name='message'
                                        placeholder="{{_('Please write here')}}..."></textarea>
                            </div>
                        </div>
                    </div>
        </div>
        <!--오더정보-->
        <div class="col-md-5">
            <div class="card shadow">
                <div class="cart-body">
                    <h5 class="ms-2 mt-3"><i class="fas fa-shopping-cart"></i> {{_("Order List")}}</h5>
                    <hr>
                    {% if cart_items %}
                    <table class="table table-stripeds table-bordereds text-start table-responsive" style="font-size:0.8rem;">
                        <thead>
                            <tr>
                                <th>{{_('Product')}}</th>
                                <th>{{_('Qty')}}</th>
                                <th>{{_('Spec')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart_items %}
                            <tr>
                                <td>{{ item.product.title}}<br>{{item.product.e_title}}</td>
                                <td>{{ item.product_qty}}</td>
                                <td>{{ item.product.spec}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="p-2 d-flex justify-content-center">
                        {% comment %} <a href="#myModal" type="submit" value="Submit" name="submit" class="btn btn-primary" data-bs-toggle="modal">Submit</a> {% endcomment %}
                    <button class="btn btn-primary" type="submit" name="submit" value="Submit" data-bs-toggle="modal" data-bs-target="#myModal">{{_('Proceed to Checkout')}}</button>
                    </div>
                    {% else %}
                    <h5 class="p-2">{% trans "Empty Order List" %}...</h5>
                    {% endif %}
                </div>
            </div>
        </div>
    </form>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body center-block">
          <div class="progress">
            <div class="progress-bar bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
              
            </div>
          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog --> 
  </div><!-- /.modal -->
{% endblock content %}

templates/store/email_order_cancel.html
주문번호 : {{tk_number}}  주문이 취소되었습니다.

문의사항있으시면, (02)9748-1400으로 연락주세요.

감사합니다

Gomaps Pty Ltd.

templates/store/email_order_completed.html
안녕하세요.

주문내용은 아래와 같습니다.

주문번호 : {{tk_number}}

배송지 : {{company_e_name}}, {{address}}

자세한 주문내역은 아래 링크를 클릭하시면 됩니다.

http://127.0.0.1:8000/order-view/{{tk_number}}



문의사항있으시면, (02)9748-1400으로 연락주세요.

감사합니다

Gomaps Pty Ltd.

templates/store/product_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="container bg-trasparent my-4" style="position: relative;">
    <h3 class>{{ category.title }}({{category.e_title}})</h3>
    <hr>
    <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3 infinite-container">
        {% for product in products %}
        <div class="col-6 infinite-item">
            <div class="card h-100 shadow-sm">
                <a href="{% url 'store:product_detail' product.category.slug product.id %}">
                    <img src="{{product.image.url}}" class="card-img-top rounded-bottom" alt="Product_image">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{product.title}}<br>
                            <span class="text-muted"
                                style="font-size:0.7rem;">{{product.e_title}}<br>SKU:{{product.bar_code}}</span></h5>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

templates/store/search.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<!-- Card-->
<main>
    <div class="container bg-trasparent my-4 search-container" style="position: relative;">
        <h3 class="mt-1"><i class="fa-solid fa-magnifying-glass"></i> {{ _('Search result') }}</h3>
        <hr>
        <div class="search">
            <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
                {% for item in search_data %}
                <div class="col-6">
                    <div class="card h-100 shadow-sm product_data">
                        <a href="{% url 'store:product_detail' item.category.slug item.id %}">
                            <img src="{{item.image.url}}" class="card-img-top" alt="Product_image">
                            <div class="label-top">
                                <span class="fa-stack fa-1x">
                                    <i class="fa-regular fa-circle fa-stack-2x"></i>
                                    <span class="fa-stack-1x">{{forloop.counter}}</span>
                                </span>
                            </div>
                            <div class="card-body text-center" style="height: 7rem;">
                                   <h5 class="card-title">{{item.title}}<br>
                                    <span class="text-muted" style="font-size:0.7rem;">{{item.e_title}}</span>
                                    <br>SKU:{{item.bar_code}}
                                </h5>

                            </div>
                        </a>
                        <div class="text-center my-2 product_data">
                            <div class="row">
                                {% csrf_token %}  <!--JQuery를 이용해서 카트에 넣기위해 -->
                                <input type="hidden" class="prod_id" id='cart-content' value="{{item.id}}" \>
                                {% comment %} <div class="col-md-6 p-1">
                                    <button type="button" class="btn btn-primary btn-sm addToCartBtn">
                                        {{_('Order')}} <i class="bi bi-bag"></i></button>
                                </div> {% endcomment %}
                                <div class="col-md-12 p-1">
                                        <button type="button" class="btn btn-warning btn-sm addToWishBtn" data-item-id="{{ item.id }}">
                                         {{_('Favorite')}} <i class="bi bi-star"></i></button>
                                </div>
                            </div>                           
                        </div>                
                    </div>                        
                </div>
                     <!-- Modal HTML -->
                     <div id="wishModal" class="modal fade" tabindex="-1">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h6 class="modal-title">{{_('Confirmation')}}</h6>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                                </div>
                                <div class="modal-body">
                                    <p>{{_('Do you want to delete this item?')}}</p>
                                    <p class="text-secondary"><small></small></p>
                                </div>
                                <div class="modal-footer product_data">
                                    <input type="hidden" class="prod_id" id='cart-content' value="{{item.id}}">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{_('Cancel')}}</button>
                                   <button type="button" class="btn btn-danger delete_wish_item">{{_('Delete')}}</button>
                                </div>
                            </div>
                        </div>
                     </div>
                     <!--End Modal--> 
            {% endfor %}

        </div>
    </div>

</main>

{% endblock %}